[build]
builder = "nixpacks"

[deploy]
startCommand = "python start_fastmcp_server.py"
healthcheckPath = "http://localhost:8001/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8000"
